import pdfkit
from jinja2 import Template
from datetime import datetime
from config import WKHTMLTOPDF_PATH

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LeadSiphon Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; line-height: 1.6; }
        .header, .footer { text-align: center; }
        .invoice-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .invoice-table th, .invoice-table td { border: 1px solid #ddd; padding: 8px; }
        .lead-entry { border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; border-radius: 5px; }
        .section { margin-top: 10px; }
        .secondary-tag { color: #999; font-size: 0.85em; }
    </style>
</head>
<body>

<div class="header">
    <h1>LeadSiphon Report</h1>
    <p><strong>Date:</strong> {{ date }}</p>
    <p>Your tailored business lead report for <strong>{{ service }}</strong>.</p>
</div>

<h2>📦 Invoice Summary</h2>
<table class="invoice-table">
    <tr>
        <th>Description</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total</th>
    </tr>
    <tr>
        <td>Custom Business Leads</td>
        <td>{{ lead_count }}</td>
        <td>${{ "%.2f"|format(unit_price) }}</td>
        <td><strong>${{ "%.2f"|format(total_price) }}</strong></td>
    </tr>
</table>

{% for lead in leads %}
    <div class="lead-entry">
        <h2>{{ lead.name }} {% if lead.source == "secondary" %}<span class="secondary-tag">(Secondary Niche)</span>{% endif %}</h2>
        <p><strong>Website:</strong> {{ lead.website or 'N/A' }}</p>
        <p><strong>Address:</strong> {{ lead.address or 'N/A' }}</p>

        <div class="section">
            <h3>Opportunities</h3>
            <p>{{ lead.opportunities }}</p>
        </div>

        <div class="section">
            <h3>Suggested Pitch</h3>
            <p>{{ lead.pitch }}</p>
        </div>

        <div class="section">
            <h3>Why Now</h3>
            <p>{{ lead.why_now }}</p>
        </div>

        <div class="section">
            <h3>Growth Signals</h3>
            <p>{{ lead.growth }}</p>
        </div>
    </div>
{% endfor %}

<div class="footer">
    <small>Generated by LeadSiphon - Instant AI-powered Lead Packs<br>&copy; {{ date }}</small>
</div>

</body>
</html>
"""

def create_report_html(leads, niche, location, service, total_price):
    today = datetime.now().strftime("%B %d, %Y")
    unit_price = round(total_price / len(leads), 2) if leads else total_price

    template = Template(HTML_TEMPLATE)
    return template.render(
        leads=leads,
        niche=niche,
        location=location,
        service=service,
        lead_count=len(leads),
        unit_price=unit_price,
        total_price=total_price,
        date=today
    )

def save_report_as_pdf(html_content, output_filename):
    if not WKHTMLTOPDF_PATH:
        raise RuntimeError("⚠️ wkhtmltopdf path is not set. Check your configuration.")

    config = pdfkit.configuration(wkhtmltopdf=WKHTMLTOPDF_PATH)
    pdfkit.from_string(html_content, output_filename, configuration=config)
    return output_filename
